name: mp_chart
description: A Flutter chart package just like AndroidMPChart, apply easy to use chart for Flutter.
version: 0.3.1
homepage: https://github.com/SunPointed/MPFlutterChart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.1
  path_provider: ^1.1.0
  screenshot: ^0.1.1
  path_drawing: ^0.4.1
  image_gallery_saver: ^1.2.2
  optimized_gesture_detector:
    git:
      url: https://github.com/LemonNicholas/OptimizedGestureDetector.git
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

